### ISSUE TITLE
README file

### ISSUE THREAD

**Issue by Xccci** [UBC-MDS/522-wine-quality-32#15]
We need to update the README.md to include the below information as well.
<img width="897" alt="image" src="https://github.com/user-attachments/assets/1616b909-9e4f-4900-9094-430f201f015b">
- Project Title
- List of Contributors/Authors
- Short summary of the project
- How to run our analysis (maybe we just need to add details on how to run the script)
- Names of the licences as well?

**Comment by Abdul-Rahmann** [comment]
@shashankhs11 
- I think it will be better to have the contributors name in full
- Also the summary says we're using logistic regression and random forest, but we use decision tree instead.

**Comment by shashankhs11** [comment]
On it!

**Comment by Abdul-Rahmann** [comment]
Looks good, thanks!
