### ISSUE TITLE
Issue: Repeated EDA plots

### ISSUE THREAD

**Issue by Abdul-Rahmann** [UBC-MDS/522-wine-quality-32#3]
There are duplicated EDA plots (vertically) for the individual features. See image below for more context.

![visualization1](https://github.com/user-attachments/assets/e267b2c6-02c7-49de-a450-f36d120b2c36)

**Comment by Xccci** [comment]
Can we use boxplot or guitar plot to make a quick summary for our dataset?

**Comment by Abdul-Rahmann** [comment]
@Xccci  Are you suggesting we use a boxplot/guitar plot instead or we should add that too?

**Comment by Xccci** [comment]
I think we can replace it with box/guitar plot since there are too many plots. We can focuse on data analysis.

**Comment by shashankhs11** [comment]
I think the bar plots here gives us a fair idea about the distribution of our dataset. Hence, the PR related to this issue is approved and merged. Hence closing this issue.
