### ISSUE TITLE
Github actions doesn't get triggered upon environment.yml and conda-lock file change

### ISSUE THREAD

**Issue by Abdul-Rahmann** [UBC-MDS/522-wine-quality-32#32]
@shashankhs11  could you look at this please?

**Comment by shashankhs11** [comment]
@Abdul-Rahmann - Currently `docker-publish.yml` triggers only when there is a change in the `conda-linux-64.lock` file or `Dockerfile`. Please go ahead and generate a new `.lock` file everytime you make a change in the `environment.yml` file.
